apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauth2.configSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
    bu: all
type: Opaque
data:
  # OAuth2 Proxy configuration file (base64 encoded)
  {{ .Values.oauth2.configKeys.oauth2Config }}: ""
  # Google Service Account JSON file (base64 encoded)
  {{ .Values.oauth2.configKeys.googleServiceAccount }}: "" 